# Generated by Django 3.2.1 on 2021-07-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/default_dp.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
