# Generated by Django 3.2.1 on 2021-06-16 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(blank=True, max_length=255)),
                ('bride_name', models.CharField(blank=True, max_length=255)),
                ('invoice_no', models.CharField(max_length=255)),
                ('invoice_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('due_date', models.DateField()),
                ('advance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('due', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_status', models.CharField(max_length=25)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('event_name', models.CharField(max_length=255)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.client')),
            ],
        ),
    ]
