# Generated by Django 3.2.1 on 2021-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210621_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bride_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='groom_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
