# Generated by Django 3.2.1 on 2021-06-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
