# Generated by Django 3.2.1 on 2021-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20210623_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
