# Generated by Django 3.2.1 on 2021-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoiceitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='advance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
