# Generated by Django 3.2.1 on 2021-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20210623_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='advance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_income',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
