# Generated by Django 3.2.1 on 2021-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20210623_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
