# Generated by Django 3.2.1 on 2021-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Client Is Deleted'), to='invoice.client'),
        ),
    ]
