# Generated by Django 3.2.1 on 2021-06-29 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.client'),
        ),
    ]
