# Generated by Django 3.2.1 on 2021-07-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_invoice_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='facebook_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
