# Generated by Django 3.2.1 on 2021-07-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_auto_20210707_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
