# Generated by Django 3.2.1 on 2021-07-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_client_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='facebook_name',
        ),
    ]
