# Generated by Django 3.2.1 on 2021-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_remove_client_facebook_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='descriptions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
