# Generated by Django 3.2.1 on 2021-07-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20210707_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='discription',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='descriptions',
            new_name='discount',
        ),
    ]
